#!/bin/bash
#
# void - Intrusion Detection Script 
# Package Manager Module
#
# PMS: dpkg

CONFIG_FILE_CHECK=false

## dpkg
## cd / ; md5sum --quiet -c /var/lib/dpkg/info/$PACKAGE_NAME.md5sums
### Failed:
## usr/sbin/lighttpd: FAILED
## md5sum: WARNING: 1 computed checksum did NOT match
##
### Missing:
## md5sum: usr/sbin/lighttpd: No such file or directory
## usr/sbin/lighttpd: FAILED open or read
## md5sum: WARNING: 1 listed file could not be read
function pms_run {
	CONFIG_FILE_DB="/var/cache/void_pms_dpkg.db"

	# dpkg < 1.17 doesn't support "--verify"... we need some workaround...
	if [ $(dpkg --version | egrep -o [0-9]\.[0-9]*\.[0-9]* | head -1 | cut -f2 -d.) -lt 17 ] ; then
		# We need to move to /, because 
		dir=$(pwd)
		cd /
	
		failed_packages=()
		for package in $(dpkg -l | egrep "^ii" | awk '{print $2}' | grep -A10 lighttpd) ; do	
			md5sum --quiet -c /var/lib/dpkg/info/${package}.md5sums 2>&1 | grep FAILED |\
			while read line ; do
				if [[ "$line" =~ .*FAILED.open.or.read ]] ; then
					echo "missing;/$(echo $line | cut -f1 -d:)"
				else
					echo "..5.....;;/$(echo $line | cut -f1 -d:)"
				fi
			done
		done

		# Test configfiles? If yes: Do we have a md5sum-db?
		if $CONFIG_FILE_CHECK && [ -f $CONFIG_FILE_DB ] ; then
			tmp_md5_file=$(mktemp)
	
			#FIXME: for now ignoring missing files
			egrep -v "^missing;" $CONFIG_FILE_DB >> $tmp_md5_file
		
			for file in $(md5sum --quiet -c $tmp_md5_file 2>&1 |grep FAILED); do		
				echo "..5.....;c;$(echo ${file} | cut -f1 -d:)"
			done

			rm $tmp_md5_file
		fi	
		cd "$dir"

	# On dpkg >= 1.17..
	else
		#Just changing the syntax from dpkg to rpm format...
		if $CONFIG_FILE_CHECK; then
			dpkg --verify | sed 's/\?/\./g;s/\ \ \ /;;/;s/\ c\ /;c;/'	
		else		
			dpkg --verify | sed 's/\?/\./g;s/\ \ \ /;;/;s/\ c\ /;c;/' | grep -v ";c;"
		fi
	fi

	CONFIG_FILE_CHECK=$CONFIG_FILE_CHECK pms_postrun
	
	return 0
}

function pms_postrun {
	CONFIG_FILE_DB="/var/cache/void_pms_dpkg.db"

	if $CONFIG_FILE_CHECK  && [ $(dpkg --version | egrep -o [0-9]\.[0-9]*\.[0-9]* | head -1 | cut -f2 -d.) -lt 17 ]; then
		rm $CONFIG_FILE_DB &>/dev/null
		for package in $(dpkg -l | egrep "^ii" | awk '{print $2}') ; do
			if [ -f /var/lib/dpkg/info/${package}.conffiles ] ; then
				while IFS= read line ; do 
					[ ! -x "$line" ] && echo "missing;c;$line" && continue
					md5sum "$line" 
				done < /var/lib/dpkg/info/${package}.conffiles >> $CONFIG_FILE_DB		
			fi
		done
	fi
	return 0
}

pms_run
